import React, { useEffect, useState } from "react";
import { clearToken, createApplication, deleteApplication, getAnalytics, getApplications, getCurrentUser, getToken, loginUser, registerUser, updateApplication } from "./api";
const STATUSES=["Applied","Screening","Interview","Offer","Rejected"];
const initialForm={company:"",role:"",location:"Auckland, New Zealand",status:"Applied",source:"LinkedIn",applied_date:new Date().toISOString().slice(0,10),contact_name:"",contact_email:"",job_url:"",notes:""};

export default function App(){
 const [authenticated,setAuthenticated]=useState(Boolean(getToken())); const [user,setUser]=useState(null); const [applications,setApplications]=useState([]); const [analytics,setAnalytics]=useState({total:0,applied:0,screening:0,interview:0,offer:0,rejected:0}); const [form,setForm]=useState(initialForm); const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState(""); const [message,setMessage]=useState("");
 const load=async()=>{try{const [apps,stats,me]=await Promise.all([getApplications(search,statusFilter),getAnalytics(),getCurrentUser()]);setApplications(apps);setAnalytics(stats);setUser(me);setMessage("")}catch(e){setMessage(e.message);if(!getToken()){setAuthenticated(false);setUser(null)}}};
 useEffect(()=>{if(authenticated)load()},[authenticated,search,statusFilter]);
 if(!authenticated)return <AuthScreen onAuthenticated={()=>setAuthenticated(true)}/>;
 const submit=async(e)=>{e.preventDefault();try{await createApplication(form);setForm(initialForm);await load()}catch(err){setMessage(err.message)}};
 const changeStatus=async(id,status)=>{try{await updateApplication(id,{status});await load()}catch(err){setMessage(err.message)}};
 const remove=async(id)=>{if(!window.confirm("Delete this application?"))return;try{await deleteApplication(id);await load()}catch(err){setMessage(err.message)}};
 const logout=()=>{clearToken();setAuthenticated(false);setUser(null);setApplications([])};
 return <main className="app-shell">
  <header className="topbar"><div><p className="eyebrow">Authenticated Full-Stack Portfolio Project</p><h1>JobTrack NZ</h1><p className="subtitle">Track applications, interviews, recruiters and outcomes in one private workspace.</p></div><div className="account-box"><div><strong>{user?.full_name||"JobTrack User"}</strong><span>{user?.email}</span></div><button className="secondary-button" onClick={logout}>Sign out</button></div></header>
  <section className="metrics"><Metric label="Total" value={analytics.total}/><Metric label="Applied" value={analytics.applied}/><Metric label="Screening" value={analytics.screening}/><Metric label="Interview" value={analytics.interview}/><Metric label="Offers" value={analytics.offer}/></section>
  <section className="grid"><div className="panel"><div className="panel-heading"><p className="eyebrow">New application</p><h2>Add a job</h2></div><form className="form" onSubmit={submit}>
   <Field label="Company"><input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})} placeholder="e.g. Xero"/></Field>
   <Field label="Role"><input required value={form.role} onChange={e=>setForm({...form,role:e.target.value})} placeholder="e.g. Graduate Software Developer"/></Field>
   <div className="form-row"><Field label="Location"><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></Field></div>
   <div className="form-row"><Field label="Source"><input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Field><Field label="Applied date"><input type="date" required value={form.applied_date} onChange={e=>setForm({...form,applied_date:e.target.value})}/></Field></div>
   <Field label="Job URL"><input value={form.job_url} onChange={e=>setForm({...form,job_url:e.target.value})} placeholder="https://..."/></Field>
   <Field label="Notes"><textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button className="primary" type="submit">Add application</button></form>{message&&<p className="message">{message}</p>}</div>
   <div className="panel"><div className="panel-heading"><p className="eyebrow">Private pipeline</p><h2>Your applications</h2></div><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company or role..."/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><div className="application-list">{applications.length===0?<div className="empty">No applications found yet.</div>:applications.map(app=><article className="application-card" key={app.id}><div className="card-top"><div><h3>{app.role}</h3><p>{app.company}</p></div><span className={`status status-${app.status.toLowerCase()}`}>{app.status}</span></div><div className="meta"><span>{app.location||"Location not set"}</span><span>{app.applied_date}</span><span>{app.source||"Source not set"}</span></div>{app.notes&&<p className="notes">{app.notes}</p>}<div className="card-actions"><select value={app.status} onChange={e=>changeStatus(app.id,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select>{app.job_url&&<a href={app.job_url} target="_blank" rel="noopener noreferrer">View job ↗</a>}<button className="danger" onClick={()=>remove(app.id)}>Delete</button></div></article>)}</div></div>
  </section></main>
}

function AuthScreen({onAuthenticated}){const [mode,setMode]=useState("login"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{if(mode==="register")await registerUser({full_name:fullName,email,password});await loginUser(email,password);onAuthenticated()}catch(err){setError(err.message)}finally{setBusy(false)}};return <main className="auth-shell"><section className="auth-brand"><p className="eyebrow">React + FastAPI + PostgreSQL</p><h1>JobTrack NZ</h1><p>A secure full-stack application for managing job applications and recruitment outcomes.</p><div className="auth-features"><span>JWT Authentication</span><span>Argon2 Password Hashing</span><span>Protected REST API</span><span>User-Specific Data</span></div></section><section className="auth-card"><p className="eyebrow">{mode==="login"?"Welcome back":"Create your account"}</p><h2>{mode==="login"?"Sign in":"Register"}</h2><form className="form" onSubmit={submit}>{mode==="register"&&<Field label="Full name"><input required minLength="2" value={fullName} onChange={e=>setFullName(e.target.value)}/></Field>}<Field label="Email"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Password"><input type="password" required minLength="8" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/></Field>{error&&<p className="auth-error">{error}</p>}<button className="primary" type="submit" disabled={busy}>{busy?"Please wait...":mode==="login"?"Sign in":"Create account"}</button></form><button className="auth-switch" onClick={()=>{setMode(mode==="login"?"register":"login");setError("")}}>{mode==="login"?"New to JobTrack? Create an account":"Already have an account? Sign in"}</button></section></main>}
function Metric({label,value}){return <div className="metric-card"><strong>{value}</strong><span>{label}</span></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
